# Generated by Django 3.2.5 on 2023-01-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-created_at', '-pk')},
        ),
    ]
