# Generated by Django 4.2.3 on 2023-07-18 22:34

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_alter_expense_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CLOTHES": "Roupas",
                            "CNPJ": "CNPJ",
                            "FOOD": "Alimentação",
                            "GIFT": "Presentes",
                            "HEALTHCARE": "Saúde",
                            "HOUSE": "Casa",
                            "OTHER": "Outros",
                            "RECREATION": "Lazer",
                            "SUPERMARKET": "Supermercado",
                            "TRANSPORT": "Transporte",
                            "TRIP": "Viagem",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="source",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "BANK_SLIP": "Boleto",
                            "BANK_TRANSFER": "Transferência bancária",
                            "CREDIT_CARD": "Cartão de crédito",
                            "DEBIT_CARD": "Cartão de débito",
                            "MONEY": "Dinheiro",
                            "SETTLE_UP": "Settle Up",
                        }
                    )
                ],
            ),
        ),
    ]
