# Generated by Django 4.2.3 on 2023-08-28 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_alter_expense_category_alter_expense_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={},
        ),
        migrations.AddField(
            model_name="expense",
            name="installment_number",
            field=models.PositiveSmallIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="installments_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="installments_qty",
            field=models.PositiveSmallIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("installments_id__isnull", True),
                        ("installment_number__isnull", True),
                        ("installments_qty__isnull", True),
                    ),
                    models.Q(
                        ("installments_id__isnull", False),
                        ("installment_number__isnull", False),
                        ("installments_qty__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="installment_values_all_null_or_all_filled",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("installments_id__isnull", True), ("is_fixed", True)),
                    ("is_fixed", False),
                    _connector="OR",
                ),
                name="fixed_expense_must_not_have_installments",
            ),
        ),
    ]
