# Generated by Django 4.2.3 on 2023-08-31 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.models_utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0005_alter_expense_options_expense_installment_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="price",
            new_name="value",
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=18)),
                ("description", models.CharField(max_length=300)),
                (
                    "created_at",
                    models.DateField(default=shared.models_utils.serializable_today_function),
                ),
                ("is_fixed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
