# Generated by Django 4.2.3 on 2023-11-05 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_alter_expense_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="installment_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="installments_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="installments_qty",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(2)]
            ),
        ),
    ]
