# Generated by Django 4.2.3 on 2024-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0009_alter_expense_value_alter_revenue_value_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="recurring_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="installments_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
