# Generated by Django 4.2.3 on 2024-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0010_expense_recurring_id_alter_expense_installments_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="recurring_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
