# Generated by Django 4.2.3 on 2024-12-21 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0012_alter_expense_category_alter_expense_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="RevenueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "hex_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            djchoices.choices.ChoicesValidator(
                                {
                                    "#5F7CB2": "Azul 3",
                                    "#61A78F": "Verde 2",
                                    "#6CCCC6": "Verde 3",
                                    "#7A9FE5": "Azul 2",
                                    "#906C96": "Roxo 2",
                                    "#906CCC": "Roxo 1",
                                    "#A3C4DA": "Azul 1",
                                    "#C6CB9C": "Verde 1",
                                    "#CA7F45": "Laranja 1",
                                    "#CB5F61": "Vermelho 1",
                                    "#CC6CC8": "Rosa 1",
                                    "#D4C05C": "Amarelo 2",
                                    "#D6A8D4": "Rosa 2",
                                    "#D8A548": "Amarelo 1",
                                    "#DAADAE": "Rosa 4",
                                    "#E57A96": "Rosa 3",
                                }
                            )
                        ],
                    ),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="revenue",
            name="expanded_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenues",
                to="expenses.revenuecategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuecategory",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="revenuecategory__name__user__unique_together"
            ),
        ),
    ]
