# Generated by Django 4.2.3 on 2024-12-24 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0013_revenue_category_revenuecategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="expenses", to="expenses.expensetag"
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="revenues", to="expenses.revenuetag"
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuetag",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="revenuetag__name__user__unique_together"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensetag",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="expensetag__name__user__unique_together"
            ),
        ),
    ]
