# Generated by Django 4.2.3 on 2025-03-05 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.models_utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0014_revenuetag_expensetag_expense_tags_revenue_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operation_date",
                    models.DateField(default=shared.models_utils.serializable_today_function),
                ),
                ("total", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
