# Generated by Django 5.2.3 on 2026-01-08 21:37

from django.db import migrations


def backfill_bank_accounts(apps, schema_editor):
    BankAccount = apps.get_model("expenses", "BankAccount")
    Expense = apps.get_model("expenses", "Expense")
    Revenue = apps.get_model("expenses", "Revenue")

    for bank_account in BankAccount.objects.all():
        # Set existing accounts as default and active
        bank_account.is_default = True
        bank_account.is_active = True
        bank_account.save(update_fields=["is_default", "is_active"])

        # Backfill all expenses to this account
        Expense.objects.filter(user_id=bank_account.user_id).update(
            bank_account=bank_account
        )

        # Backfill all revenues to this account
        Revenue.objects.filter(user_id=bank_account.user_id).update(
            bank_account=bank_account
        )


def reverse_backfill(apps, schema_editor):
    Expense = apps.get_model("expenses", "Expense")
    Revenue = apps.get_model("expenses", "Revenue")

    Expense.objects.all().update(bank_account=None)
    Revenue.objects.all().update(bank_account=None)


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0016_bankaccount_credit_card_bill_day_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_bank_accounts, reverse_backfill),
    ]
