# Generated by Django 5.2.3 on 2026-01-12 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0017_backfill_bank_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revenues",
                to="expenses.bankaccount",
            ),
        ),
    ]
