# Generated by Django 5.2.3 on 2026-01-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0018_alter_expense_bank_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="exclude_from_fire",
            field=models.BooleanField(default=False),
        ),
    ]
