# Generated by Django 5.2.3 on 2026-03-07 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0019_add_exclude_from_fire_to_expense_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["user", "created_at"], name="expenses_ex_user_id_88f6c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenue",
            index=models.Index(
                fields=["user", "created_at"], name="expenses_re_user_id_8fe438_idx"
            ),
        ),
    ]
