# Generated by Django 5.2.3 on 2026-03-17 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0020_expense_expenses_ex_user_id_88f6c0_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bankaccountsnapshot",
            index=models.Index(
                fields=["user", "operation_date"], name="expenses_ba_user_id_25b238_idx"
            ),
        ),
    ]
