# Generated by Django 6.1.2 on 2026-10-07 17:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0021_bankaccountsnapshot_expenses_ba_user_id_25b238_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("description", config="simple"),
                name="expenses_desc_search_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="revenue",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("description", config="simple"),
                name="revenues_desc_search_gin",
            ),
        ),
    ]
