FROM node:16.13.1-alpine3.13

WORKDIR /app/react

#enable hot-reloading
ENV CHOKIDAR_USEPOLLING=true

COPY ./package.json .
RUN npm install --legacy-peer-deps
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
