# Generated by Django 3.2.5 on 2021-08-17 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('RECREATION', 'Lazer'), ('SUPERMARKET', 'Supermercado'), ('FOOD', 'Alimentação'), ('CLOTHES', 'Roupas'), ('GIFT', 'Presentes'), ('HEALTHCARE', 'Saúde'), ('HOUSE', 'Casa'), ('TRANSPORT', 'Transporte'), ('TRIP', 'Viagem'), ('OTHER', 'Outros')], max_length=20)),
                ('created_at', models.DateField(default=shared.models_utils.serializable_today_function)),
                ('source', models.CharField(choices=[('CREDIT_CARD', 'Cartão de crédito'), ('DEBIT_CARD', 'Cartão de débito'), ('BANK_TRANSFER', 'Transferência bancária'), ('MONEY', 'Dinheiro'), ('BANK_SLIP', 'Boleto'), ('SETTLE_UP', 'Settle Up')], max_length=20)),
                ('is_fixed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
