# Generated by Django 3.2.5 on 2021-07-28 00:44

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('STOCK', 'Ação B3'), ('STOCK USA', 'Ação EUA'), ('CRIPTO', 'Criptoativos'), ('FII', 'Fundo de Investimento Imobiliário')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('created_at', models.DateField(default=api.models.today)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PassiveIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIVIDEND', 'Dividendo'), ('JCP', 'Juros sobre capital próprio')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('received_at', models.DateField(default=api.models.today)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='api.asset')),
            ],
        ),
    ]
