"""FIRE return-series calculations, validation, and rendering."""

from decimal import Decimal

MonthlySeries = dict[str, Decimal]

FIRE_RETURN_SERIES_KEYS = (
    "IBOV",
    "IFIX",
    "SPY",
    "VTI",
    "VT",
    "VWRL",
    "BTC",
    "CMBI10",
    "CDI",
    "IMA_S",
    "IRF_M_1",
    "IRF_M_1_PLUS",
    "IMA_B_5",
    "IMA_B_5_PLUS",
    "IMA_GERAL_EX_C",
    "CASH",
)


def validate_fire_return_series(series: dict[str, MonthlySeries]) -> None:
    expected = set(FIRE_RETURN_SERIES_KEYS)
    actual = set(series)
    missing = sorted(expected - actual)
    if missing:
        raise ValueError(f"Missing FIRE return series: {', '.join(missing)}")
    unexpected = sorted(actual - expected)
    if unexpected:
        raise ValueError(f"Unexpected FIRE return series: {', '.join(unexpected)}")
    for key in FIRE_RETURN_SERIES_KEYS:
        if not series[key]:
            raise ValueError(f"FIRE return series {key} is empty")


def to_real_returns(nominal: MonthlySeries, ipca: MonthlySeries) -> MonthlySeries:
    return {
        month: (Decimal(1) + value) / (Decimal(1) + ipca[month]) - Decimal(1)
        for month, value in nominal.items()
        if month in ipca
    }


def foreign_to_brl_returns(
    foreign: MonthlySeries, usd_brl: MonthlySeries
) -> MonthlySeries:
    return {
        month: (Decimal(1) + value) * (Decimal(1) + usd_brl[month]) - Decimal(1)
        for month, value in foreign.items()
        if month in usd_brl
    }


def normalize_foreign_real_returns(
    *,
    foreign_total_returns: MonthlySeries,
    usd_brl_returns: MonthlySeries,
    ipca_returns: MonthlySeries,
) -> MonthlySeries:
    return to_real_returns(
        foreign_to_brl_returns(foreign_total_returns, usd_brl_returns),
        ipca_returns,
    )


def cash_real_returns(ipca: MonthlySeries) -> MonthlySeries:
    return {
        month: Decimal(1) / (Decimal(1) + value) - Decimal(1)
        for month, value in ipca.items()
    }


def _format_return(value: Decimal) -> str:
    return format(value.quantize(Decimal("0.0000000001")), "f")


def render_fire_returns_ts(series: dict[str, MonthlySeries]) -> str:
    entries = []
    for key in FIRE_RETURN_SERIES_KEYS:
        if key not in series:
            continue
        months = sorted(series[key])
        month_values = ", ".join(f'"{month}"' for month in months)
        return_values = ", ".join(_format_return(series[key][month]) for month in months)
        entries.append(
            f'  {key}: {{ label: "{key}", months: [{month_values}], '
            f"realReturns: [{return_values}] }},"
        )

    return (
        "// Auto-generated by "
        "django/variable_income_assets/scripts.py::generate_fire_returns_ts\n"
        'import type { FireReturnSeriesKey } from "./fireReturnTypes";\n\n'
        "export type FireReturnSeries = {\n"
        "  label: string;\n"
        "  months: readonly string[];\n"
        "  realReturns: readonly number[];\n"
        "};\n\n"
        "export const FIRE_RETURN_SERIES: Record<FireReturnSeriesKey, FireReturnSeries> = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
