// Auto-generated by django/variable_income_assets/scripts.py::generate_fire_returns_ts
// Source: NEFIN Risk Factors + B3 IFIX yearly variation + BCB SGS 433 (IPCA).
// NEFIN period: 2001–2025 (25 complete years).
// IFIX period: 2011–2025 (15 complete years).
// Real annual returns = (1 + nominal) / (1 + IPCA) - 1.

export const FIRE_RETURNS_YEARS: readonly number[] = [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025];

// Brazilian market portfolio (value-weighted) — real annual returns.
export const EQUITY_REAL_RETURNS: readonly number[] = [-0.065654, -0.074816, 0.615348, 0.181278, 0.259876, 0.289332, 0.364821, -0.425980, 0.669092, -0.002529, -0.127578, 0.067395, -0.080591, -0.093496, -0.202818, 0.277768, 0.237483, 0.103725, 0.293669, -0.007753, -0.184778, -0.044752, 0.192119, -0.122988, 0.182531];

// Risk-free (SELIC-based) — real annual returns.
export const FIXED_INCOME_REAL_RETURNS: readonly number[] = [0.095523, 0.060861, 0.122652, 0.078232, 0.124472, 0.111884, 0.067378, 0.060132, 0.050528, 0.035892, 0.047119, 0.021411, 0.020022, 0.039917, 0.022159, 0.071204, 0.064073, 0.024452, 0.014056, -0.017707, -0.049104, 0.064035, 0.079182, 0.056987, 0.096432];

export const IFIX_YEARS: readonly number[] = [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025];

// IFIX (Brazilian REIT index, total return) — real annual returns.
export const IFIX_REAL_RETURNS: readonly number[] = [0.093959, 0.275905, -0.175061, -0.086156, -0.047559, 0.245013, 0.159913, 0.018068, 0.303664, -0.141195, -0.112129, -0.033699, 0.103984, -0.102272, 0.161950];
