// Auto-generated by django/variable_income_assets/scripts.py::generate_fire_returns_ts
// Source: B3 IBOV + B3 IFIX + BCB SGS 4391 (CDI) + BCB SGS 433 (IPCA).
// IBOV/CDI/IPCA period: 1995–2025 (31 complete years).
// IFIX period: 2011–2025 (15 complete years).
// Real annual returns = (1 + nominal) / (1 + IPCA) - 1.

export const FIRE_RETURNS_YEARS: readonly number[] = [1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025];

// IBOV (Ibovespa total return, BRL) — real annual returns.
export const EQUITY_REAL_RETURNS: readonly number[] = [-0.193372, 0.494634, 0.376468, -0.345482, 1.312537, -0.157537, -0.173620, -0.262481, 0.805425, 0.094863, 0.208374, 0.288830, 0.375194, -0.444989, 0.751067, -0.045932, -0.231097, 0.014723, -0.202118, -0.087582, -0.216731, 0.307134, 0.232244, 0.108796, 0.261516, -0.015324, -0.199778, -0.010386, 0.168804, -0.144914, 0.284761];

// CDI accumulated monthly — real annual returns.
export const FIXED_INCOME_REAL_RETURNS: readonly number[] = [0.250662, 0.160004, 0.184122, 0.264903, 0.148547, 0.107160, 0.089037, 0.058295, 0.127737, 0.079502, 0.125907, 0.115311, 0.070436, 0.061174, 0.053276, 0.036367, 0.047798, 0.024266, 0.020320, 0.041487, 0.023401, 0.072506, 0.067865, 0.025692, 0.015722, -0.016873, -0.051111, 0.062350, 0.080358, 0.057777, 0.096566];

export const IFIX_YEARS: readonly number[] = [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025];

// IFIX (Brazilian REIT index, total return) — real annual returns.
export const IFIX_REAL_RETURNS: readonly number[] = [0.093949, 0.275907, -0.175017, -0.086182, -0.047577, 0.245058, 0.159876, 0.018070, 0.303618, -0.141194, -0.112104, -0.033674, 0.103949, -0.102303, 0.161931];
