# Generated by Django 3.2.5 on 2021-09-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('REVOKED', 'Revoked'), ('REJECTED', 'Rejected'), ('RETRY', 'Retry'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20),
        ),
    ]
