# Generated by Django 4.2.3 on 2023-07-18 22:34

from django.db import migrations, models
import djchoices.choices
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_auto_20220119_0153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskhistory",
            name="opened_at",
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="notification_display_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="taskhistory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="taskhistory",
            name="state",
            field=models.CharField(
                default="PENDING",
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "FAILURE": "Failure",
                            "PENDING": "Pending",
                            "STARTED": "Started",
                            "SUCCESS": "Success",
                        }
                    )
                ],
            ),
        ),
    ]
