# Generated by Django 3.2.5 on 2021-12-14 20:58

import authentication.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20210921_2347"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cpf", models.CharField(blank=True, max_length=14, null=True, unique=True)),
                (
                    "cei_password",
                    authentication.fields.EncryptedField(blank=True, max_length=1000, null=True),
                ),
                (
                    "kucoin_api_key",
                    authentication.fields.EncryptedField(blank=True, max_length=1000, null=True),
                ),
                (
                    "kucoin_api_secret",
                    authentication.fields.EncryptedField(blank=True, max_length=1000, null=True),
                ),
                (
                    "kucoin_api_passphrase",
                    authentication.fields.EncryptedField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="cei_password",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="cpf",
        ),
        migrations.AddConstraint(
            model_name="integrationsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cpf__isnull", True), ("cei_password__isnull", True)),
                    models.Q(("cpf__isnull", False), ("cei_password__isnull", False)),
                    _connector="OR",
                ),
                name="cei_secrets_all_null_or_all_filled",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationsecret",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kucoin_api_key__isnull", True),
                        ("kucoin_api_secret__isnull", True),
                        ("kucoin_api_passphrase__isnull", True),
                    ),
                    models.Q(
                        ("kucoin_api_key__isnull", False),
                        ("kucoin_api_secret__isnull", False),
                        ("kucoin_api_passphrase__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="kucoin_secrets_all_null_or_all_filled",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="secrets",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="authentication.integrationsecret",
            ),
        ),
    ]
