# Generated by Django 3.2.5 on 2022-01-04 12:24

import authentication.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211214_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsecret',
            name='binance_api_key',
            field=authentication.fields.EncryptedField(blank=True, max_length=1000, null=True),
        ),
    ]
