# Generated by Django 3.2.5 on 2022-01-08 14:29

import authentication.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_integrationsecret_binance_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsecret',
            name='binance_api_secret',
            field=authentication.fields.EncryptedField(blank=True, max_length=1000, null=True),
        ),
    ]
