# Generated by Django 3.2.5 on 2022-01-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_integrationsecret_binance_secrets_all_null_or_all_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_asset_price_integration',
            field=models.BooleanField(default=True),
        ),
    ]
