# Generated by Django 4.2.2 on 2023-06-29 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_customuser_has_asset_price_integration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="has_asset_price_integration",
        ),
    ]
