# Generated by Django 4.2.3 on 2023-07-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_remove_customuser_has_asset_price_integration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="integrationsecret",
            name="cei_secrets_all_null_or_all_filled",
        ),
        migrations.RemoveField(
            model_name="integrationsecret",
            name="cei_password",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
