# Generated by Django 4.2.3 on 2023-09-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
