# Generated by Django 4.2.3 on 2023-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_customuser_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_investments_integrations_module_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_investments_module_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_personal_finances_module_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
