# Generated by Django 4.2.3 on 2023-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0012_customuser_is_investments_integrations_module_enabled_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_default_payment_method",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("INACTIVE", "Inativa"),
                    ("TRIALING", "Em período de teste"),
                    ("ACTIVE", "Ativa"),
                    ("PAST_DUE", "Vencida"),
                    ("UNPAID", "Sem pagamento"),
                    ("CANCELED", "Cancelada"),
                    ("INCOMPLETE", "Incompleta"),
                    ("INCOMPLETE_EXPIRED", "Incompleta e expirada"),
                    ("PAUSED", "Pausada"),
                ],
                default="INACTIVE",
                max_length=25,
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_investments_integrations_module_enabled", True),
                    ("is_investments_module_enabled", False),
                    _negated=True,
                ),
                name="investments_integrations_module_cant_be_enabled_alone",
            ),
        ),
    ]
