# Generated by Django 4.2.3 on 2024-02-27 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0014_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="credit_card_bill_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
