# Generated by Django 4.2.3

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0015_customuser_credit_card_bill_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="planning_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
