# Generated by Django 5.2.3 on 2026-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_customuser_planning_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
