FROM python:3.13-bookworm

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends build-essential gcc postgresql-client
RUN pip install uv

WORKDIR /app/django

COPY ./entrypoint.sh /app/django/entrypoint.sh
RUN chmod +x /app/django/entrypoint.sh

ENTRYPOINT ["sh", "/app/django/entrypoint.sh"]
CMD ["uv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
