# Generated by Django 3.2.5 on 2021-10-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0002_alter_revenue_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ('-created_at',)},
        ),
    ]
