# Generated by Django 3.2.5 on 2021-08-19 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shared.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('STOCK', 'Ação B3'), ('STOCK USA', 'Ação EUA'), ('CRIPTO', 'Criptoativos'), ('FII', 'Fundo de Investimento Imobiliário')], max_length=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-code',),
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=15)),
                ('created_at', models.DateField(default=shared.models_utils.serializable_today_function)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='variable_income_assets.asset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PassiveIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIVIDEND', 'Dividendo'), ('JCP', 'Juros sobre capital próprio'), ('INCOME', 'Rendimento')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('credited_at', models.DateField(blank=True, null=True)),
                ('payment_forecast', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='variable_income_assets.asset')),
            ],
            options={
                'ordering': ('-credited_at', '-payment_forecast', '-amount'),
            },
        ),
    ]
