# Generated by Django 3.2.5 on 2021-11-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable_income_assets', '0002_auto_20210927_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='passiveincome',
            options={'ordering': ('-operation_date', '-amount')},
        ),
        migrations.RemoveField(
            model_name='passiveincome',
            name='credited_at',
        ),
        migrations.RemoveField(
            model_name='passiveincome',
            name='payment_forecast',
        ),
        migrations.AddField(
            model_name='passiveincome',
            name='event_type',
            field=models.CharField(choices=[('PROVISIONED', 'Provisionado'), ('CREDITED', 'Creditado')], default='PROVISIONED', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passiveincome',
            name='operation_date',
            field=models.DateField(default='2021-11-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('STOCK', 'Ação B3'), ('STOCK_USA', 'Ação EUA'), ('CRIPTO', 'Criptoativos'), ('FII', 'Fundo de Investimento Imobiliário')], max_length=10),
        ),
    ]
