# Generated by Django 3.2.5 on 2021-11-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable_income_assets', '0003_auto_20211112_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
    ]
