# Generated by Django 3.2.5 on 2021-12-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable_income_assets', '0006_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='asset',
            name='current_price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
