# Generated by Django 3.2.5 on 2022-01-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable_income_assets', '0007_auto_20211225_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('STOCK', 'Ação B3'), ('STOCK_USA', 'Ação EUA'), ('CRYPTO', 'Criptoativos'), ('FII', 'Fundo de Investimento Imobiliário')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real'), ('USD', 'Dólar')], default='BRL', max_length=6),
        ),
    ]
