# Generated by Django 3.2.5 on 2022-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable_income_assets', '0009_alter_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='objective',
            field=models.CharField(choices=[('GROWTH', 'Crescimento'), ('DIVIDEND', 'Dividendo'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(choices=[('INDUSTRIALS', 'Bens industriais'), ('COMMUNICATION', 'Comunicações'), ('CONSUMER DISCRETIONARY', 'Consumo cíclico'), ('CONSUMER STAPLES', 'Consumo não cíclico'), ('FINANCIALS', 'Financeiro'), ('MATERIALS', 'Materiais básicos'), ('RAW ENERGY', 'Petróleo, gás e biocombustíveis'), ('HEALTH CARE', 'Saúde'), ('TECH', 'Tecnologia'), ('UTILITIES', 'Utilidade Pública'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=50),
        ),
    ]
