# Generated by Django 3.2.5 on 2023-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable_income_assets', '0010_auto_20220605_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sector',
            field=models.CharField(choices=[('INDUSTRIALS', 'Bens industriais'), ('COMMUNICATION', 'Comunicações'), ('CONSUMER DISCRETIONARY', 'Consumo cíclico'), ('CONSUMER STAPLES', 'Consumo não cíclico'), ('FINANCIALS', 'Financeiro'), ('MATERIALS', 'Materiais básicos'), ('RAW ENERGY', 'Petróleo, gás e biocombustíveis'), ('HEALTH CARE', 'Saúde'), ('TECH', 'Tecnologia'), ('UTILITIES', 'Utilidade pública'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=50),
        ),
    ]
