# Generated by Django 4.2.2 on 2023-06-28 23:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import variable_income_assets.choices


class Migration(migrations.Migration):
    dependencies = [
        ("variable_income_assets", "0012_auto_20230323_2218"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                (
                    "type",
                    models.CharField(
                        max_length=10,
                        validators=[variable_income_assets.choices.AssetTypes.custom_validator],
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        default="UNKNOWN",
                        max_length=50,
                        validators=[variable_income_assets.choices.AssetSectors.custom_validator],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        max_length=6,
                        validators=[
                            variable_income_assets.choices.TransactionCurrencies.custom_validator
                        ],
                    ),
                ),
                ("current_price", models.DecimalField(decimal_places=6, max_digits=13)),
                (
                    "current_price_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="assetreadmodel",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="assetreadmodel",
            name="current_price_updated_at",
        ),
        migrations.AddField(
            model_name="assetreadmodel",
            name="total_bought",
            field=models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=15),
        ),
        migrations.AddField(
            model_name="assetreadmodel",
            name="total_invested_adjusted",
            field=models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=15),
        ),
        migrations.AddConstraint(
            model_name="assetmetadata",
            constraint=models.UniqueConstraint(
                fields=("code", "type", "currency"),
                name="code__type__currency__unique_together",
            ),
        ),
        migrations.AddField(
            model_name="assetreadmodel",
            name="metadata",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_read_assets",
                to="variable_income_assets.assetmetadata",
            ),
        ),
    ]
