# Generated by Django 4.2.2 on 2023-06-29 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "variable_income_assets",
            "0013_assetmetadata_remove_assetreadmodel_current_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="current_price_updated_at",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="assetreadmodel",
            name="roi",
        ),
        migrations.RemoveField(
            model_name="assetreadmodel",
            name="roi_percentage",
        ),
    ]
