# Generated by Django 4.2.2 on 2023-06-29 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("variable_income_assets", "0014_remove_asset_current_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetreadmodel",
            name="sector",
        ),
    ]
