# Generated by Django 4.2.3 on 2023-07-18 22:34

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):
    dependencies = [
        (
            "variable_income_assets",
            "0016_alter_asset_options_alter_passiveincome_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passiveincome",
            name="fetched_by",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="fetched_by",
        ),
        migrations.AlterField(
            model_name="asset",
            name="currency",
            field=models.CharField(
                blank=True,
                max_length=6,
                validators=[
                    djchoices.choices.ChoicesValidator({"BRL": "Real", "USD": "Dólar"})
                ],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="objective",
            field=models.CharField(
                default="UNKNOWN",
                max_length=50,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "DIVIDEND": "Dividendo",
                            "GROWTH": "Crescimento",
                            "UNKNOWN": "Desconhecido",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Criptoativos",
                            "FII": "Fundo de Investimento Imobiliário",
                            "STOCK": "Ação B3",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetmetadata",
            name="currency",
            field=models.CharField(
                max_length=6,
                validators=[
                    djchoices.choices.ChoicesValidator({"BRL": "Real", "USD": "Dólar"})
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetmetadata",
            name="sector",
            field=models.CharField(
                default="UNKNOWN",
                max_length=50,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "COMMUNICATION": "Comunicações",
                            "CONSUMER DISCRETIONARY": "Consumo não cíclico",
                            "CONSUMER STAPLES": "Consumo cíclico",
                            "FINANCIALS": "Financeiro",
                            "HEALTH CARE": "Saúde",
                            "INDUSTRIALS": "Bens industriais",
                            "MATERIALS": "Materiais básicos",
                            "RAW ENERGY": "Petróleo, gás e biocombustíveis",
                            "TECH": "Tecnologia",
                            "UNKNOWN": "Desconhecido",
                            "UTILITIES": "Utilidade pública",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetmetadata",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Criptoativos",
                            "FII": "Fundo de Investimento Imobiliário",
                            "STOCK": "Ação B3",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetreadmodel",
            name="currency",
            field=models.CharField(
                blank=True,
                max_length=6,
                validators=[
                    djchoices.choices.ChoicesValidator({"BRL": "Real", "USD": "Dólar"})
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetreadmodel",
            name="objective",
            field=models.CharField(
                default="UNKNOWN",
                max_length=50,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "DIVIDEND": "Dividendo",
                            "GROWTH": "Crescimento",
                            "UNKNOWN": "Desconhecido",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetreadmodel",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Criptoativos",
                            "FII": "Fundo de Investimento Imobiliário",
                            "STOCK": "Ação B3",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="passiveincome",
            name="event_type",
            field=models.CharField(
                max_length=11,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"CREDITED": "Creditado", "PROVISIONED": "Provisionado"}
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="passiveincome",
            name="type",
            field=models.CharField(
                max_length=8,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "DIVIDEND": "Dividendo",
                            "INCOME": "Rendimento",
                            "JCP": "Juros sobre capital próprio",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                max_length=4,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"BUY": "Compra", "SELL": "Venda"}
                    )
                ],
            ),
        ),
    ]
