# Generated by Django 4.2.3 on 2024-07-24 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices
import shared.models_utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "variable_income_assets",
            "0018_rename_total_bought_assetreadmodel_normalized_total_bought_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "FII": "FII",
                            "STOCK": "Ação BR",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetmetadata",
            name="sector",
            field=models.CharField(
                default="UNKNOWN",
                max_length=50,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "COMMUNICATION": "Comunicações",
                            "CONSUMER DISCRETIONARY": "Consumo não cíclico",
                            "CONSUMER STAPLES": "Consumo cíclico",
                            "FINANCIALS": "Financeiro",
                            "HEALTH CARE": "Saúde",
                            "INDUSTRIALS": "Bens industriais",
                            "MATERIALS": "Materiais básicos",
                            "RAW ENERGY": "Petróleo e derivados",
                            "TECH": "Tecnologia",
                            "UNKNOWN": "Desconhecido",
                            "UTILITIES": "Utilidade pública",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetmetadata",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "FII": "FII",
                            "STOCK": "Ação BR",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetreadmodel",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "FII": "FII",
                            "STOCK": "Ação BR",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="AssetsTotalInvestedSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operation_date",
                    models.DateField(default=shared.models_utils.serializable_today_function),
                ),
                ("total", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_total_invested_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
