# Generated by Django 4.2.3 on 2024-12-29 00:41

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):
    dependencies = [
        ("variable_income_assets", "0019_alter_asset_type_alter_assetmetadata_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passiveincome",
            name="type",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "DIVIDEND": "Dividendo",
                            "INCOME": "Rendimento",
                            "JCP": "Juros sobre capital próprio",
                            "REIMBURSEMENT": "Reembolso",
                        }
                    )
                ],
            ),
        ),
    ]
