# Generated by Django 4.2.3 on 2025-01-17 15:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):
    dependencies = [
        ("variable_income_assets", "0020_alter_passiveincome_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assetmetadata",
            name="code__type__currency__unique_together",
        ),
        migrations.AddField(
            model_name="asset",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="assetmetadata",
            name="asset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="variable_income_assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetreadmodel",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="code",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "FII": "FII",
                            "FIXED_BR": "Renda fixa BR",
                            "STOCK": "Ação BR",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetmetadata",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "FII": "FII",
                            "FIXED_BR": "Renda fixa BR",
                            "STOCK": "Ação BR",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetreadmodel",
            name="code",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="assetreadmodel",
            name="type",
            field=models.CharField(
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "FII": "FII",
                            "FIXED_BR": "Renda fixa BR",
                            "STOCK": "Ação BR",
                            "STOCK_USA": "Ação EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="current_currency_conversion_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("1.0"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.DecimalField(decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddConstraint(
            model_name="assetmetadata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset__isnull", True)),
                fields=("code", "type", "currency"),
                name="code__type__currency__unique_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetmetadata",
            constraint=models.CheckConstraint(
                check=models.Q(("asset__isnull", True), ("type", "FIXED_BR"), _connector="OR"),
                name="only_fixed_assets_can_have_a_direct_metadata",
            ),
        ),
    ]
