# Generated by Django 5.2.3 on 2025-08-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_income_assets", "0022_alter_assetmetadata_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmetadata",
            name="current_price",
            field=models.DecimalField(decimal_places=10, max_digits=17),
        ),
    ]
