# Generated by Django 5.2.3 on 2025-12-20 20:03

import djchoices.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_income_assets", "0023_alter_assetmetadata_current_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_currency",
                    models.CharField(
                        max_length=6,
                        validators=[
                            djchoices.choices.ChoicesValidator({"BRL": "Real", "USD": "Dólar"})
                        ],
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        max_length=6,
                        validators=[
                            djchoices.choices.ChoicesValidator({"BRL": "Real", "USD": "Dólar"})
                        ],
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_currency", "to_currency"),
                        name="from_currency__to_currency__unique_together",
                    )
                ],
            },
        ),
    ]
