# Generated by Django 5.2.3 on 2025-12-20 20:26

from decimal import Decimal

from variable_income_assets.choices import Currencies

from django.db import migrations


def create_dollar_to_brl_rate(apps, schema_editor):
    ConversionRate = apps.get_model("variable_income_assets", "ConversionRate")
    ConversionRate.objects.create(
        from_currency=Currencies.dollar,
        to_currency=Currencies.real,
        value=Decimal("5.54"),
    )


def reverse_migration(apps, schema_editor):
    ConversionRate = apps.get_model("variable_income_assets", "ConversionRate")
    ConversionRate.objects.filter(
        from_currency=Currencies.dollar, to_currency=Currencies.real
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("variable_income_assets", "0024_add_conversion_rate_model"),
    ]

    operations = [
        migrations.RunPython(create_dollar_to_brl_rate, reverse_migration),
    ]
