# Generated by Django 5.2.3 on 2026-01-01 20:36

import djchoices.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_income_assets", "0025_create_dollar_to_brl_conversion_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="liquidity_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"AT_MATURITY": "Somente no Vencimento", "DAILY": "Liquidez Diária"}
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="maturity_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetreadmodel",
            name="liquidity_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"AT_MATURITY": "Somente no Vencimento", "DAILY": "Liquidez Diária"}
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="assetreadmodel",
            name="maturity_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
