# Generated by Django 5.2.3 on 2026-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_income_assets", "0026_asset_liquidity_type_asset_maturity_date_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assetreadmodel",
            index=models.Index(
                fields=["user_id", "quantity_balance"], name="variable_in_user_id_20bad5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetreadmodel",
            index=models.Index(
                fields=["user_id", "normalized_closed_roi"], name="variable_in_user_id_8b5ace_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passiveincome",
            index=models.Index(fields=["operation_date"], name="variable_in_operati_61f01e_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["operation_date"], name="variable_in_operati_373cf8_idx"),
        ),
    ]
