# Generated by Django 5.2.3 on 2026-03-17 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_income_assets", "0027_assetreadmodel_variable_in_user_id_20bad5_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assetstotalinvestedsnapshot",
            index=models.Index(
                fields=["user", "operation_date"], name="variable_in_user_id_f3e729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passiveincome",
            index=models.Index(
                fields=["asset", "event_type", "operation_date"],
                name="variable_in_asset_i_b6b6c7_idx",
            ),
        ),
    ]
