# Generated by Django 5.2.3 on 2026-05-13 00:31

import djchoices.choices
from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def backfill_irpf_columns(apps, schema_editor):
    # No bonificações exist in historical data, so irpf_price == price for every
    # existing transaction, and irpf_*_total_bought == *_total_bought for every
    # existing closed operation.
    Transaction = apps.get_model("variable_income_assets", "Transaction")
    AssetClosedOperation = apps.get_model("variable_income_assets", "AssetClosedOperation")
    Transaction.objects.update(irpf_price=F("price"))
    AssetClosedOperation.objects.update(
        irpf_total_bought=F("total_bought"),
        irpf_normalized_total_bought=F("normalized_total_bought"),
    )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "variable_income_assets",
            "0028_assetstotalinvestedsnapshot_variable_in_user_id_f3e729_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assetclosedoperation",
            name="irpf_normalized_total_bought",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="assetclosedoperation",
            name="irpf_total_bought",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="irpf_price",
            field=models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"BONIFICACAO": "Bonificação", "BUY": "Compra", "SELL": "Venda"}
                    )
                ],
            ),
        ),
        migrations.RunPython(backfill_irpf_columns, reverse_noop),
    ]
