# Generated by Django 5.2.3 on 2026-09-17 14:29

from django.db import migrations, models

import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        (
            "variable_income_assets",
            "0029_assetclosedoperation_irpf_normalized_total_bought_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="indexer",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"CDI": "CDI", "IPCA": "IPCA", "PREFIXED": "Prefixado", "SELIC": "Selic"}
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="assetreadmodel",
            name="indexer",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=10,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {"CDI": "CDI", "IPCA": "IPCA", "PREFIXED": "Prefixado", "SELIC": "Selic"}
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "EQUITY_GLOBAL": "Renda variável Global",
                            "FII": "FII",
                            "FIXED_BR": "Renda fixa BR",
                            "STOCK": "Renda variável BR",
                            "STOCK_USA": "Renda variável EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetmetadata",
            name="type",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "EQUITY_GLOBAL": "Renda variável Global",
                            "FII": "FII",
                            "FIXED_BR": "Renda fixa BR",
                            "STOCK": "Renda variável BR",
                            "STOCK_USA": "Renda variável EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assetreadmodel",
            name="type",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "CRYPTO": "Cripto",
                            "EQUITY_GLOBAL": "Renda variável Global",
                            "FII": "FII",
                            "FIXED_BR": "Renda fixa BR",
                            "STOCK": "Renda variável BR",
                            "STOCK_USA": "Renda variável EUA",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="passiveincome",
            name="type",
            field=models.CharField(
                max_length=20,
                validators=[
                    djchoices.choices.ChoicesValidator(
                        {
                            "DIVIDEND": "Dividendo",
                            "INCOME": "Rendimento",
                            "INTEREST": "Juros",
                            "JCP": "Juros sobre capital próprio",
                            "REIMBURSEMENT": "Reembolso",
                        }
                    )
                ],
            ),
        ),
    ]
